apiVersion: v1
kind: Service
metadata:
  name: testapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: testapp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: testapp
  name: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: testapp
  template:
    metadata:
      labels:
        run: testapp
    spec:
      containers:
      - image: nginx
        name: nginx