kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  output.conf: |
    [OUTPUT]
      Name  es
      Match *
      Host  search-opensearch-public-4tgrkrkrh6vlz43xcradevk3va.us-west-2.es.amazonaws.com
      Port  443
      AWS_Auth On
      AWS_Region us-west-2
      tls On
      Index fargate_log
      Type  _doc
      